### ISSUE TITLE
SV_BuildSoundMsg

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [In-line/metamod_unprecacher#15]
SV_BuildSoundMsg: player/pl_wade1.wav not precached (0) 
SV_BuildSoundMsg: player/pl_wade2.wav not precached (0)

In log's

**Comment by afwn90cj93201nixr2e1re** [comment]
changelevel failed: 'hldm1' not found on server.
;(
По достижению timeout'a без использования каких либо доп мапменеджеров. Чистый рехлдс - Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 19:08:32 Oct  7 2016 (909)
ReHLDS API version 2.13

**Comment by In-line** [comment]
@shelru, Какие настройки?

**Comment by afwn90cj93201nixr2e1re** [comment]
Стандарт с блокировкой звуков.

**Comment by In-line** [comment]
Такая функция уже удалена из модуля. Обновить нужно.
