### ISSUE TITLE
Бинарники и исходы

### ISSUE THREAD

**Issue by kenofJums** [In-line/metamod_unprecacher#25]
CMake Error at test/CMakeLists.txt:13 (target_compile_features):
  Unknown CMake command "target_compile_features".

И где собственно говоря бинарники?

**Comment by In-line** [comment]
releases посмотри и у тебя CMake древний

**Comment by kenofJums** [comment]
@In-line 
```
(general) root@Ubuntu1404x64:~/hlds/mmz# cmake .                                -- The C compiler identification is GNU 4.9.4
-- The CXX compiler identification is GNU 4.9.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done

-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /root/hlds/mmz
```

Как сошка называться должна и где лежать? не могу никак найти

**Comment by In-line** [comment]
Зачем самому компилировать, если не собираешься разработкой заниматься?

Инструкции по компилированию можно найти в README.md, но тебе нужно ещё выполнить команду
```
make -j$((2 * `getconf _NPROCESSORS_ONLN`)) # Multicore build
```

**Comment by kenofJums** [comment]
`(general) root@Ubuntu1404x64:~/hlds/mmz# make -j$((2 * `getconf _NPROCESSORS_ONLN`))
Scanning dependencies of target unprecacher
Scanning dependencies of target unprecacher_static
[  7%] [ 14%] Building CXX object CMakeFiles/unprecacher.dir/src/unprecacheoptions.cpp.o
Building CXX object CMakeFiles/unprecacher_static.dir/src/unprecacheoptions.cpp.o
[ 21%] [ 28%] Building CXX object CMakeFiles/unprecacher_static.dir/src/module.cpp.o
Building CXX object CMakeFiles/unprecacher.dir/src/module.cpp.o
[ 42%] [ 35%] Building CXX object CMakeFiles/unprecacher.dir/src/config.cpp.o
Building CXX object CMakeFiles/unprecacher_static.dir/src/config.cpp.o
[ 50%] [ 57%] Building CXX object CMakeFiles/unprecacher_static.dir/src/logger.cpp.o
Building CXX object CMakeFiles/unprecacher.dir/src/logger.cpp.o
[ 64%] Building CXX object CMakeFiles/unprecacher.dir/src/helper/string_utils.cpp.o
[ 71%] Building CXX object CMakeFiles/unprecacher_static.dir/src/helper/string_utils.cpp.o
/root/hlds/mmz/src/helper/string_utils.cpp: In function ‘std::string str_put_time(const tm*, const char*)’:
/root/hlds/mmz/src/helper/string_utils.cpp:182:8: error: ‘put_time’ is not a member of ‘std’
  ss << std::put_time(tmb, fmt);
        ^
/root/hlds/mmz/src/helper/string_utils.cpp: In function ‘std::string str_put_time(const tm*, const char*)’:
/root/hlds/mmz/src/helper/string_utils.cpp:182:8: error: ‘put_time’ is not a member of ‘std’
  ss << std::put_time(tmb, fmt);
        ^
make[2]: *** [CMakeFiles/unprecacher_static.dir/src/helper/string_utils.cpp.o] Error 1
make[2]: *** [CMakeFiles/unprecacher.dir/src/helper/string_utils.cpp.o] Error 1
make[1]: *** [CMakeFiles/unprecacher_static.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/unprecacher.dir/all] Error 2
make: *** [all] Error 2
`

Потому что я не нашел бинарников.

**Comment by In-line** [comment]
Я же написал, что в releases нужно смотреть
https://github.com/In-line/metamod_unprecacher/releases

**Comment by In-line** [comment]
А для компиляции древние gcc не подойдут, нужна версия `>4.8`

**Comment by kenofJums** [comment]
Укажи это в ридми.

**Comment by In-line** [comment]
Про версию GCC указано в комментариях к командам для билда :)

**Comment by In-line** [comment]
А про releases должно быть и так понятно.

**Comment by kenofJums** [comment]
Фигово указано, ведь пут тайм добавили лишь в 5 ветке, в 49 его все еще нет.

**Comment by In-line** [comment]
Если нет больше вопросов, то закрываю issue.

**Comment by kenofJums** [comment]
```
(general) root@Ubuntu1404x64:~/hlds/mmz# make -j$((2 * `getconf _NPROCESSORS_ONLN`))
[  7%] [ 14%] Building CXX object CMakeFiles/unprecacher.dir/src/main.cpp.o
Building CXX object CMakeFiles/unprecacher_static.dir/src/main.cpp.o
In file included from /root/hlds/mmz/src/main.cpp:34:0:
/root/hlds/mmz/src/helper/external_api.h:6:20: fatal error: extdll.h: No such file or directory
 #include <extdll.h>
                    ^
compilation terminated.
In file included from /root/hlds/mmz/src/main.cpp:34:0:
/root/hlds/mmz/src/helper/external_api.h:6:20: fatal error: extdll.h: No such file or directory
 #include <extdll.h>
                    ^
compilation terminated.
make[2]: *** [CMakeFiles/unprecacher_static.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/unprecacher_static.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/unprecacher.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/unprecacher.dir/all] Error 2
make: *** [all] Error 2
(general) root@Ubuntu1404x64:~/hlds/mmz#

```

**Comment by In-line** [comment]
https://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules

**Comment by kenofJums** [comment]
```

(general) root@Ubuntu1404x64:~/hlds/mmz# make -j$((2 * `getconf _NPROCESSORS_ONLN`))
Scanning dependencies of target unprecacher_static
Scanning dependencies of target unprecacher
[  7%] [ 14%] Building CXX object CMakeFiles/unprecacher_static.dir/src/unprecacheoptions.cpp.o
Building CXX object CMakeFiles/unprecacher.dir/src/unprecacheoptions.cpp.o
[ 21%] [ 28%] Building CXX object CMakeFiles/unprecacher.dir/src/module.cpp.o
Building CXX object CMakeFiles/unprecacher_static.dir/src/module.cpp.o
[ 42%] [ 35%] Building CXX object CMakeFiles/unprecacher.dir/src/config.cpp.o
Building CXX object CMakeFiles/unprecacher_static.dir/src/config.cpp.o
[ 57%] [ 50%] Building CXX object CMakeFiles/unprecacher.dir/src/logger.cpp.o
Building CXX object CMakeFiles/unprecacher_static.dir/src/logger.cpp.o
[ 64%] Building CXX object CMakeFiles/unprecacher.dir/src/helper/string_utils.cpp.o
[ 71%] Building CXX object CMakeFiles/unprecacher_static.dir/src/helper/string_utils.cpp.o
[ 78%] [ 85%] Building CXX object CMakeFiles/unprecacher_static.dir/src/main.cpp.o
Building CXX object CMakeFiles/unprecacher.dir/src/main.cpp.o
Linking CXX static library libunprecacher_static.a
Linking CXX shared library libunprecacher.so
[ 85%] Built target unprecacher_static
[ 92%] Generating runner.cpp
Traceback (most recent call last):
  File "/usr/bin/cxxtestgen", line 3, in <module>
    import cxxtest.cxxtestgen
  File "/usr/share/cxxtest/cxxtest/__init__.py", line 33, in <module>
    from cxxtest.cxxtestgen import *
  File "/usr/share/cxxtest/cxxtest/cxxtestgen.py", line 18, in <module>
    import __release__
ModuleNotFoundError: No module named '__release__'
make[2]: *** [test/runner.cpp] Error 1
make[1]: *** [test/CMakeFiles/tester.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 92%] Built target unprecacher
make: *** [all] Error 2
```

**Comment by kenofJums** [comment]
gcc?
